version: '2'

services:
  mongo:
    image: mongo:latest
    volumes:
      - "./mongo/data/db:/data/db"
    ports:
      - 27017:27017

  web:
    image: nginx
    volumes:
      - "./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf"
      - "./nginx/log:/var/log/nginx"
      - "../frontend:/usr/share/nginx/html"
    ports:
      - "80:80"
    command: /bin/bash -c "nginx && tail -f /var/log/nginx/*.log"
